---
- name: Backup ARRIS
  connection: network_cli
  gather_facts: false
  debugger: never
  gather_facts: no
  hosts: NE

  tasks:

    - name: Creo el directorio para guardar el backup
      file:
        path: /io/cel_core/backup/CMTS/{{inventory_hostname}}/configs/
        state: directory
      delegate_to: localhost

    - name: Backup E6K
      ios_command:
        commands: 
          -  configure no pagination
          -  show running-config
      register: command_output_arris
      ignore_errors: true

    - name: Debug
      debug:
        msg: "{{command_output_arris}}"
      when: command_output_arris is defined
      delegate_to: localhost

    - name: Copio salida de E6K
      copy:
        content: "{{ command_output_arris.stdout[1] }}"
        dest: /io/cel_core/backup/CMTS/{{inventory_hostname}}/configs/ARRIS_{{inventory_hostname}}_{{now().strftime("%d-%m-%y_%H-%M")}}.bkp 
      delegate_to: localhost