---
- name: Backup CMTS
  connection: network_cli
  gather_facts: false
  hosts: CMTS_CISCO

  tasks:
    - name: Backup CBR8
      ios_command:
        commands: 
          -  terminal length 0
          -  show running-config
      register: command_output_cisco
      when: "'CMTS_CISCO' in group_names" 
      ignore_errors: true

    #- debug:
    #    msg: "{{ command_output_cisco.stdout }}"

    - name: Creo el directorio para guardar el backup
      file:
        path: /usr/local/backup/CMTS/{{nombre}}/configs/
        state: directory
      delegate_to: localhost

    - name: Copio salida de CBR8
      copy:
        content: "{{ command_output_cisco.stdout[1] }}"
        dest: /usr/local/backup/CMTS/{{nombre}}/configs/CISCO_{{nombre}}_{{now().strftime("%d-%m-%y_%H-%M")}}.bkp
      delegate_to: localhost

