---
- name: Backup CBR8
  connection: network_cli
  gather_facts: false
  debugger: never
  gather_facts: no
  hosts: NE

  tasks:

    - name: Creo el directorio para guardar el backup
      file:
        path: /io/cel_core/backup/CMTS/{{inventory_hostname}}/configs/
        state: directory
      delegate_to: localhost

    - name: Backup CBR8
      ios_command:
        commands: 
          -  terminal length 0
          -  show running-config
      register: command_output_cisco
      ignore_errors: true

    - name: Debug
      debug:
        msg: "{{command_output_cisco}}"
      when: command_output_cisco is defined
      delegate_to: localhost

    - name: Copio salida de CBR8
      copy:
        content: "{{ command_output_cisco.stdout[1] }}"
        dest: /io/cel_core/backup/CMTS/{{inventory_hostname}}/configs/CISCO_{{inventory_hostname}}_{{now().strftime("%d-%m-%y_%H-%M")}}.bkp 
      delegate_to: localhost