---
- name: Prueba interfaces equipo
  connection: telnet
  gather_facts: false
  hosts: OLT

  tasks:
    - name: -- Display Version --
      telnet_command:
        prompt: ".*"	 
        command:
          - enable
          - display version
      register: info_hw



    
