---
- name: Version CMTS
  connection: network_cli
  gather_facts: false
  hosts: CMTS_CASA

  tasks:
    - name: -Hago un CAT del Show run --
      shell: "cat `ls -rt /io/cel_core/backup/CMTS/{{nombre}}/configs/*.bkp | tail -1` | sed -n '/^! Boot/,/!/p'"
      register: versionc100g
      delegate_to: localhost

    - debug:
        msg: "{{versionc100g}}"

    - name: Creo el directorio para guardar la version
      file:
        path: /io/cel_core/backup/CMTS/{{nombre}}/configs/version
        state: directory
      delegate_to: localhost

    - name: Copio la version de C100G
      copy:
        content: "{{ versionc100g.stdout }}"
        dest: /io/cel_core/backup/CMTS/{{nombre}}/configs/version/CASA_{{nombre}}.cfg
      delegate_to: localhost