---
- name: Version CMTS
  connection: network_cli
  gather_facts: false
  hosts: CMTS_ARRIS

  tasks:
    - name: -Hago un CAT del Show run --
      shell: "cat `ls -rt /io/cel_core/backup/CMTS/{{nombre}}/configs/*.bkp | tail -1` | sed -n '/^#/,/configure/p'"
      register: versione6k
      delegate_to: localhost

    - debug:
        msg: "{{versione6k}}"

    - name: Creo el directorio para guardar la version
      file:
        path: /io/cel_core/backup/CMTS/{{nombre}}/configs/version
        state: directory
      delegate_to: localhost

    - name: Copio la version de E6K
      copy:
        content: "{{ versione6k.stdout }}"
        dest: /io/cel_core/backup/CMTS/{{nombre}}/configs/version/ARRIS_{{nombre}}.cfg
      delegate_to: localhost