---

- name: -- GENERATE CONFIG INTERFACE WIDEBAND - LINECARD {{ item }} --
  set_fact:
    texto: "{{ lookup('template', '{{ folder_templates }}/config_CBR8_wideband_cable.j2') }}"

- name: -- APPEND CONFIGURATION DE FILE {{ inventory_hostname }}.cfg --
  shell: echo "{{texto}}" >> {{folder_config}}/{{inventory_hostname}}.cfg
  delegate_to: localhost   